### ISSUE TITLE
AMPD: Conduct Interviews on users who use API's - To Do in PI 2

### ISSUE THREAD

**Issue by krdeaven** [US-EPA-CAMD/HCD#25]
Notes from PI Backlog Refinement:

Goal: Be able to download more data at once than we can do right now - stay away from technology dependent and focus on business need

This is about large and custom data sets, not just pre-packaged

Need to figure out the right user community who will use this feature

Andrew question: Should we show someone what this could look like?

Discussion of filter criteria that allow the users to customize reports - could be design exercise as well as research along with this

**Comment by nsameerun** [comment]
Notes from PI Backlog Refinement:

Ming and Michelle: 
With respect to API data, what do you need? 
With respect to FACTS data, what do you need?

Mike and Michelle: What is the MVP for CAMD Suite. What are we working toward? 

Michelle: What research do we need to prioritize and what research do we need to hold back on?

**Comment by nsameerun** [comment]
Michelle and Jorga: What functionality do we need to create, in order for us to sunset ECMPS.

Jorga: Identity what AMPD query tool will look like in order to identify how ECMPS will want to pull the data in a new way, to display in AMPD.

Research Goal: Identify the functionality and feature set that is a priority for users.

**Comment by nsameerun** [comment]
Archive because the issue is duplicate to issue #38
